name: windows

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ '2.4.9', '2.5.7', '2.6.5' ]
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update -i
      - name: Setup ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Dependencies
        run: TEST_TOOL=rubygems util/ci.sh before_script
        shell: bash
      - name: Run Test
        # create a symlink for git to a folder without a space, needed for CI only
        run: |
          New-Item -Path "C:\git" -ItemType Junction -Value "C:\Program Files\Git" 1> $null
          $env:GIT = "C:\git\cmd\git.exe"
          ridk enable
          rake test
    timeout-minutes: 15
